### ISSUE TITLE
nitter.conf file gets reset on start

### ISSUE THREAD

**Issue by Latrolage** [unixfox/periodic-build-with-github-actions#9]
I'm having problems with the nitter.conf file being reset every time the container is being run. i asked the nitter repo but was redirected here  because I'm using your docker container. https://github.com/zedeus/nitter/issues/743.

 I basically can't configure any settings because they get reset every time.

Here is my `docker-compose.yml`
<details>
<summary>docker-compose.yml</summary>

```yaml
version: "3"
 
services:
 
  nitter:
    image: quay.io/unixfox/nitter:latest
    container_name: nitter
    restart: always
    depends_on:
      - redis
    volumes:
      - ./data/nitter:/data
    ports:
      - "127.0.0.1:3300:8080"
    environment:
      - REDIS_HOST="redis"
 
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server
    volumes:
      - ./data/redis:/data
      - ./data/redis/redis.conf:/etc/redis/redis.conf:ro
```
</details>
the last line about redis.conf isn't used anywhere. If i make the redis-server use that (it's just the default config file from https://github.com/redis/redis/blob/7.0/redis.conf it doesn't work anyway.

I've also tried having just `- ./data/nitter/nitter.conf:/src/nitter.conf:ro` in the volumes sections for the `nitter:` container and whilst the file does not get reset anymore, the configuration is just ignored
